### ISSUE TITLE
Request: UI 개선을 위해 수정이 필요한 부분을 찾아 제안

### ISSUE THREAD

**Issue by yujin9747** [HGU-WALAB/SW-Milege-Front#106]
# 관리자 페이지

- [x] 로그인 화면: 상단 헤더 > 로그아웃 버튼 숨기기
- [x] 로그인 화면: 좌측 사이드바 숨기기

- [x] 카테고리 화면: 우선순위를 카테고리 생성, 수정, 조회 테이블에서 빼기 
       드래그 앤 드랍으로만 조작 가능하면 좋을 것 같아요. 현재 우선순위가 중복되어도 생성이 되고, 기존 드래그 앤 드랍에 연결했던 기능이 제대로 안 돌아가요

**학생명 필터링 관련**
- [x] 학생 관리 화면: 학생 이름으로 필터링하는 것 보단 학번 필터링이 더 필요할 것 같아요
       이름은 중복 가능. 둘 다 필터링 가능하거나, 하나만 한다면 학번만
- [x] 신청자 관리 화면: 학생 필터링 > 학번 필터링으로 변경(위와 동일한 이유)
- [x] 관리자 화면: 학생명 필터링 삭제 > 직번 필터링 추가
- [x] 마일리지 조회 화면: 학생명 필터링 > 학번 필터링으로 변경(위와 동일한 이유)

**Comment by ohinhyuk** [comment]
카테고리 화면: 드롭다운이 어떤 부분을 말하는 건가요???
학생명: 이름이 중복이 가능하더라도 사용자 관점에서 학생 이름으로 필터링 하는게 더 직관적이지 않을까요??

나머지는 적용하도록 하겠습니다.

**Comment by yujin9747** [comment]
> 카테고리 화면: 드롭다운이 어떤 부분을 말하는 건가요??? 학생명: 이름이 중복이 가능하더라도 사용자 관점에서 학생 이름으로 필터링 하는게 더 직관적이지 않을까요??
> 
> 나머지는 적용하도록 하겠습니다.

드롭다운 -> 드래그 앤 드랍으로 수정했습니다. 
학번 필터링 추가하는 것으로 결정

**Comment by ohinhyuk** [comment]
드래그 앤 드랍은 잘 작동하는데 우선 순위가 같은것 끼리 바꾸면 변화가 없습니다.
현재 우선 순위를 적지 않으면 모두 0으로 생성 되는데 폼에서 없앤 뒤 현재 로직대로 진해앟면 우선 순위가 0으로 모두 같기 때문에 순서 조절이 불가능 합니다.

우선 순위를 auto increment로 바꾸고 우선 순위를 내림 차순으로 보이도록 하는 것 어떨까요??
우선 순위 기준 솔팅은 프론트에서 진행 되기 때문에 우선 순위 auto increment로 바꾸는 것만 진행 해주시면 됩니다.

**Comment by yujin9747** [comment]
> 드래그 앤 드랍은 잘 작동하는데 우선 순위가 같은것 끼리 바꾸면 변화가 없습니다. 현재 우선 순위를 적지 않으면 모두 0으로 생성 되는데 폼에서 없앤 뒤 현재 로직대로 진해앟면 우선 순위가 0으로 모두 같기 때문에 순서 조절이 불가능 합니다.
> 
> 우선 순위를 auto increment로 바꾸고 우선 순위를 내림 차순으로 보이도록 하는 것 어떨까요?? 우선 순위 기준 솔팅은 프론트에서 진행 되기 때문에 우선 순위 auto increment로 바꾸는 것만 진행 해주시면 됩니다. @yujin9747

백엔드 레포 issue#188번으로 진행중입니다.
