### ISSUE TITLE
BUG: 백엔드 팀원이 발견한 버그 리스트를 정리한다.

### ISSUE THREAD

**Issue by yujin9747** [HGU-WALAB/SW-Milege-Front#107]
# 관리자 페이지

### 사이드바에서 마일리지 글로벌 항목 선택

재현 경로
1. 사이드바에서 "마일리지 글로벌 항목"을 선택할 시
2. "마일리지 학기별 항목"이 초록색으로 표시된다. 

기대 결과
마일리지 글로벌 항목 선택 시 마일리지 글로벌 항목 메뉴가 초록색으로 표시되어야 한다. 

### 사이드바에서 마일리지 학기별 항목 선택

재현 경로
1. 사이드바에서 "마일리지 학기별 항목"을 선택할 시
2. "마일리지 조회"가 초록색으로 표시된다. 

기대 결과
마일리지 학기별 항목 선택 시 마일리지 학기별 항목 메뉴가 초록색으로 표시되어야 한다.

**Comment by ohinhyuk** [comment]
적용하도록 하겠습니다
