### ISSUE TITLE
BUG: 중복 적립 가능 여부는 "학기별 항목"의 속성이다. 

### ISSUE THREAD

**Issue by yujin9747** [HGU-WALAB/SW-Milege-Front#109]
**Bug Description**
중복 적립 O/X는 글로벌 항목을 생성할 때가 아니라 학기별 항목을 생성할 때 입력할 수 있어야한다. 
DB에는 isMulti라는 이름으로 존재하는 값이며, 이는 한 학생이 학기별 항목을 여러번 적립할 수 있는지를 결정한다. 

**To Reproduce**
1. 글로벌 항목 생성 시 중복 적립 여부 OX 입력 칸이 존재함. 
2. 글로벌 항목 생성 후, 수정 모달을 띄웠을 때 중복 적립 여부 값이 백엔드에서 오지 않으니 OX 둘 중 어떤 것도 선택되지 않은 상태로 나옴. 
3. 학기별 항목 생성 시 중복 적립 여부 OX 입력 칸이 존재하지 않음. 
4. 학기별 항목 수정 시 중복 적립 여부를 확인하고 수정할 수 없음. 

**Expected behavior**
중복 적립 여부는 학기별 항목을 생성할 때 지정할 수 있어야 한다.

**Comment by ohinhyuk** [comment]
적용하였습니다.
