### ISSUE TITLE
Request: UI 개선 사항을 찾아서 제안

### ISSUE THREAD

**Issue by yujin9747** [HGU-WALAB/SW-Milege-Front#110]
**글로벌 항목**
- [x] 생성 및 수정 시 "항목 최대 포인트" 입력란 필요
- [x] 생성 및 수정 시 "중복 적립" 입력란 없애야 함 (중복 적립 여부는 학기별 항목에 입력해야 합니다)

**학기별 항목**
- [x] 생성 및 수정 시 "중복 적립" 입력란 필요
- [ ] 생성 시 "항목 최대 포인트"는 기본적으로 "글로벌 항목"에서 복사해 오기로 했었어요. 이 부분이 UI로 적용이 안되어 있는 것 같아요. 
       학기별 항목 생성 시 글로벌 항목에서 항목 최대 포인트를 가져와서 생성/수정 모달에 보여주면 어떨까요?
- [x] 학기별 항목 생성 시 "학기", "글로벌 항목" 미선택 시 에러 대처 수정
       
<img width="1470" alt="스크린샷 2024-01-21 오후 4 46 18" src="https://github.com/HGU-WALAB/SW-Milege-Front/assets/89755770/b0d957bb-1ca2-4837-9766-64ce56ac2f65">
<img width="1470" alt="스크린샷 2024-01-21 오후 4 48 55" src="https://github.com/HGU-WALAB/SW-Milege-Front/assets/89755770/8649e94a-9e9c-403f-be39-3c3b77be9d1f">

위의 두 에러 메세지는 사용자에게 전달하는 용도가 아니라, 프론트와 백엔드 연결 과정에서 잘못된 경우 주는 메세지라 보이는게 조금 어색하네요. 
제출 누르기 전에 학기, 글로벌 항목을 선택하라고 고지하는게 어떨까요? 

<img width="324" alt="스크린샷 2024-01-21 오후 4 50 14" src="https://github.com/HGU-WALAB/SW-Milege-Front/assets/89755770/a4aeca7f-66c9-469f-8e7f-d5d2196a18a2">
예를 들어 이런 식으로요. 

- [x] 학기별 항목 2개 이상 선택 후 삭제 버튼 눌렀을 때 "삭제가 완료되었습니다" alert 창이 삭제한 갯수만큼 나와요. 
       여러개를 한 번에 삭제할 때 삭제 되었다는 메세지가 그 갯수만큼 나오면 불편할 것 같아요. 프론트에서 처리 가능한가요? 
       아님 백엔드에서 API 만들어줘야 하나요?

**학기**

- [x] 학기 선택 드롭다운 메뉴에 현재 존재하는 학기만 넣는거 어떨까요? 
       존재하지 않는 학기를 선택해서 생성 및 수정에 실패하는 과정을 줄여주면 좋을 것 같아요
       드롭다운 메뉴를 보고 학기가 이미 생성되어 있다고 착각할 수도 있을것 같아요. 

**마일리지 기록**
- [x] 마일리지 기록 생성 시 "등록 횟수"의 기본값을 아래 이미지와 같이 0 -> 1로 변경하는 것을 제안합니다. 
       대부분 1로 등록하는 경우가 많을 것 같아요. 
       추가로, 0을 입력 시 1이상을 입력하라는 alert창은 나오지만, 
       등록 횟수를 비워둘 경우에 필수 입력 사항이라는 고지는 없는 상태예요. 
       폼 제출 시 등록 횟수가 비어있으면 빨간색으로 표시되면 좋을 것 같습니다. 
       
<img width="578" alt="스크린샷 2024-01-21 오후 7 38 06" src="https://github.com/HGU-WALAB/SW-Milege-Front/assets/89755770/1a5d34ef-7e83-4cac-99ed-ea4db3b8325e">

**Comment by ohinhyuk** [comment]
한개를 제외 하고 적용하였습니다.
체크 안된 한 개는 개발쪽에 로드가 좀 있어 추후에 추가하도록 할 계획입니다.
