### ISSUE TITLE
BUG: 카테고리 드래그 앤 드랍 기능 버그

### ISSUE THREAD

**Issue by yujin9747** [HGU-WALAB/SW-Milege-Front#111]
**Bug Description**
카테고리 생성 시 orderIdx를 auto increment 하는 부분은 백엔드 쪽에서 수정이 완료 되었어요. 
DB에 기존에 존재하던 모든 카테고리들이 중복된 orderIdx를 가지지 않고, 1씩 증가하는 orderIdx를 가지도록 수정했어요. 

이 상태에서 드래그 앤 드랍 테스트를 해 봤을 때 제대로 적용되지 않습니다. 

**To Reproduce**

상황1
1. 카테고리 페이지에서
2. 2번째 페이지로 넘어간다. 
3. 2번째 페이지의 5번째 있는 항목을 클릭해 2번째 페이지의 맨 위로 올린다.
4. 검사>네트워크 페이지를 확인해 보면 2번째 페이지에 있는 항목에 대해 수정 API가 날라가는 것이 아니라 1번째 페이지의 항목에 대해 날라가는 것을 확인할 수 있다. 하지만, 날라가는 API 의 기대 결과 조차도 DB에 반영되지 않는다. 수정 API 요청이 제대로 날라가는지 확인 필요. 

상황2
1. 카테고리 페이지에서
2. 1번째 페이지에서
3. 1번째 페이지의 5번째 항목을 클릭해 1번째 페이지의 맨 위로 올린다. 
4. 잠시 동안은 육안상 5번째 항목이 맨 위로 올라간 것 처럼 보이지만, DB에는 반영되지 않았기 때문에 새로고침하면 원래대로 돌아온다. 

**Expected behavior**

### case 1

- 위치를 이동할 카테고리의 orderIdx = 10
- 놓을 위치의 orderIdx = 5

<기대 결과>

- orderIdx가 5, 6, 7, 8, 9인 카테고리의 orderIdx는 1씩 증가한다. 
- orderIdx가 10인 카테고리의 orderIdx는 5로 변경된다. 

### case2

- 위치를 이동할 카테고리의 orderIdx = 5

- 놓을 위치의 orderIdx = 10

<기대 결과2>

- orderIdx가 6, 7, 8, 9, 10인 카테고리의 orderIdx는 1씩 감소한다. 

- orderIdx가 5인 카테고리의 orderIdx는 10으로 변경된다. 

이동할 카테고리의 orderIdx와, 놓을 위치의 orderIdx의 대소를 비교해 case1 알고리즘, case2 알고리즘 중 무엇을 적용할 것인지 결정하는 로직이 들어가야함.

**Comment by yujin9747** [comment]
![Uploading 스크린샷 2024-01-21 오후 9.30.06.png…]()

**Comment by ohinhyuk** [comment]
수정하였습니다.
