### ISSUE TITLE
4주차 변경사항 정리

### ISSUE THREAD

**Issue by Park21700305** [HGU-WALAB/SW-Milege-Front#118]
**마일리지 카테고리 **

**To Do**
- [x]  카테고리 최대 포인트 → 적립 가능 최대 마일리지
- [x] 타입 select label 수정 
- [ ] 페이지네이션 데이터 가져오기 수정

**Comment by zionhann** [comment]
- [ ] 마일리지 카테고리 : 생성시 타입 선택 삭제
- [ ] 마일리지 세부항목 : 생성시 타입 추가(드롭다운), 중복 여부 추가, `stu_type` 제거
- [ ] 학기별 마일리지 세부항목 : 중복 여부 삭제, 엑셀 업로드 버튼 삭제, 항목 수정시 지정한 학기 및 세부항목은 읽기 전용으로 변경, 추가적인 이름 지정 허용
