### ISSUE TITLE
REQUEST: API 연결 요청

### ISSUE THREAD

**Issue by yujin9747** [HGU-WALAB/SW-Milege-Front#49]
**To Do**
- [x]  마일리지 record 생성/수정 시 extraPoints 입력란 추가
- [x]  삭제가 불가능한 원인인 하위 기록 조회 api 연결
- [x]  학기별 항목에 등록된 학생 수 보여주기

**Comment by ohinhyuk** [comment]
학기별 항목 -> 마일리지 등록 페이지에 나타난 학기별 맞나요??

그리고 현재 마일리지 등록에서 사용하는 API에는
API endpoint : /api/mileage/semesters/2022-01/items
학생 수를 보내주지 않습니다.

각 항목 마다 학생수를 보내줘야 할 것 같습니다!

**Comment by yujin9747** [comment]
> 학기별 항목 -> 마일리지 등록 페이지에 나타난 학기별 맞나요??
> 
> 그리고 현재 마일리지 등록에서 사용하는 API에는 API endpoint : /api/mileage/semesters/2022-01/items 학생 수를 보내주지 않습니다.
> 
> 각 항목 마다 학생수를 보내줘야 할 것 같습니다!

학기별 항목은 마일리지 등록할 때 선택하는 학기별 항목 맞아요! 

/api/mileage/semesters/2022-01/items/records
위의 API에서 records 리스트도 함께 반환해서 여기서 등록 학생 수를 가져다가 쓸 수 있을 줄 알았는데 api가 다르네요!
/api/mileage/semesters/2022-01/items
위의 API의 기존 반환값에 "recordCount" 라는 이름으로 숫자형 반환 추가 하고 알려줄게요!

**Comment by ohinhyuk** [comment]
하위 항목 삭제 관련 Backend 이슈

https://github.com/HGU-WALAB/sw-mileage-server-kt/issues/48#issue-1879960890

현재 카테고리 , 글로벌 항목 은 완료된 상태이다.
